name: Deploy to One.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.null00.no  # Replace with your One.com server
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Directory to upload (use './' for the root of the repo)
        server-dir: /customers/2/c/5/null00.no/httpd.www/sharper-fangs/  # Target directory on the One.com server
